include $(TOPDIR)/rules.mk

PKG_NAME:=neepu-login-tool
PKG_VERSION:=1.0
PKG_RELEASE:=1

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://github.com/AsulTop/NEEPU_LoginTool_CLI_Public.git
PKG_SOURCE_VERSION:=main

include $(INCLUDE_DIR)/package.mk

define Package/neepu-login-tool
  SECTION:=utils
  CATEGORY:=Utilities
  TITLE:=NEEPU Login Tool
  DEPENDS:=+libstdcpp
endef

define Package/neepu-login-tool/description
  A login tool for NEEPU network authentication.
endef

define Build/Compile
	$(MAKE) -C $(PKG_BUILD_DIR) \
		CC="$(TARGET_CC)" \
		CXX="$(TARGET_CXX)" \
		CFLAGS="$(TARGET_CFLAGS) -I$(PKG_BUILD_DIR)/src/3rd" \
		CXXFLAGS="$(TARGET_CXXFLAGS) -I$(PKG_BUILD_DIR)/src/3rd" \
		LDFLAGS="$(TARGET_LDFLAGS)"
endef

define Package/neepu-login-tool/install
	$(INSTALL_DIR) $(1)/usr/bin
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/src/neepu-login-tool $(1)/usr/bin/
endef

$(eval $(call BuildPackage,neepu-login-tool))